# **MARFIN IN-HOUSE PROPOSAL**

## Proposal Number:

## Title of Project:

## Applicant:
J. Kevin Craig

## Principle Investigators (Must be NMFS employees):
J. Kevin Craig^1^, James Nance^2^, Katie Andrews^1^

^1^ Beaufort Laboratory, National Marine Fisheries Service, Beaufort, NC, USA  
^2^ Galveston Laboratory, National Marine Fisheries Service, Galveston, TX, USA 

## Project Objectives:  
* Characterize the temporal and spatial dynamics of incidental bycatch within the Gulf of Mexico shrimp fishery.  
* Identify the location of bycatch hotspots within the western Gulf of Mexico for total bycatch, and specifically for several federally managed finfish species including Red Snapper, Vermillian Snapper, Greater Amberjack, King Mackeral and Spanish Mackeral.  
* Evaluate the correlation between the bycatch estimates derived from fishery-independent and fishery-dependent sources.  
* Estimate the effect of shrimping effort on the spatial dyanmics of incidental catch using a variable coefficient generalized additive modeling framework.  

## Describe work to be performed:  

Fishery bycatch or the incidental capture of non-target species is critcal issue of global conservation [@kelleher2005discards via Sims2008] and management concern [@Gardner2008spatial].  Bycatch is of particlular concern for fishing gears with indiscrinante targeting (eg longline, trawls) [@Gardner2008spatial]

Fleet dynamics are spatially heterogeneous and the little is known about the relationship between the spatial distribution of fishery effort and the spatial distribution of fishery bycatch. 

Increasing interest in fishery bycatch is apparent in the peer-reviewed literature [@soykan2008why] with a number of studies focusing on the Gulf of Mexico examining issues on the feasibility of bycatch quotas [@diamond2004bycatch], bycatch species composition [Scott-Denton2012characterization], as well as population level examination of the impact of fishing on elasmobranchs [@shepherd2005direct], Atlantic croaker (*Micropogonias undulatus*)[@diamond2000population], and Red snapper (*Lutjanus campechanus*)[gallaway1998estimates].  We propose to expand on this work by utilizing fishery-dependent and independent data sets currently available for the Gulf of Mexico to examine the relationship between the spatial and temporal distribution of both shrimp fishery effort and observer reported fishery bycatch, to better understand the interaction between fishery effort, resource abundance and the spatial distribution of incidental catch.

Data sets
There are four managed data sets that house information concerning the dynamics of the Gulf shrimp fishery including three fishery-dependent monitoring data sets and a fishery-independent trawl survery.  

The fishery-dependent data sets include the Gulf Shrimp Statistics (GSS) database, an electronic log book (ELB) program, and a fishery observer program.   The GSS database contains details on landings and effort statistics for the Gulf shrimp fishery these data are collected and archived by the National Marine Fishery Service (NMFS) Galveston Laboratory, Texas.  This fishery-dependent data set, a trip-level record of vessel landings and effort for the Gulf shrimp fishery, dates back to 1960 (Nichols 1984, Poffenberger 1991, Nance 1992).  Historically, fishing effort (days fished) for the Gulf shrimp fishery is not measured directly but is estimated, based on non-random interviews conducted by NMFS port agents (Nance 1992, 2008). Constraints in the spatial and temporal resolution of the historical data as well as limitations in the accuracy of port agent assignment of fishing effort (GMFMC 1994), lead to the development of an electronic log book program (ELB) program for the Gulf shrimp fishery [@gallaway2003description].  This program designates a random sample of shrimp vessels on a trimester basis (Jan-Apr, May-Aug, Sep-Dec) to be instrumented with an ELB unit that recordes geographic position at 10 minute intervals and total time for individual shrimp tows.  Fishing effort is identified based on changes in vessel speed and comparisons among the ELB, paper logbooks, and observer records have shown that this methodology provides an accurate representation of the spatial distribution of shrimping effort [@gallaway2001development;@gallaway2000development;@gallaway2003description].  The initial years of the ELB program instrumented a small number of vessels and were considered pilot studies [@gallaway2003evaluation;@gallaway2003description], currently there are over 9 years (2005-2013) of data covering a wide region of the northwestern Gulf (Figure 1).  

```{r elbPlot, echo=FALSE, message=FALSE, warning=FALSE, fig.align='center', fig.cap="Figure 1: Spatial distribution if electronic log book (ELB) tows for 2011"}
library(maptools)
library(maps)
library(mapdata)
elb<-read.csv("C:\\Users\\Kevin.Purcell\\Documents\\GitHub\\MARFIN_2014\\elbdata.csv")
plot(elb$slat[elb$yr==2011] ~ elb$slon[elb$yr==2011],
     xlim=c(-97,-88),
     ylim=c(24.5,30.5),
     xlab="Lon",
     ylab="Lat")
map("state",fill=T,col="gray",add=T)
text(-90,25,"2011 Locations", font=2)

```

The fishery observer program was instituted in the Gulf as a result of federal legistlation.... Details about the observer program from Scott-Denton.  

The fishery-independent data derives from the Southeast Area Monitoring and Assessment Program (SEAMAP) survey [@eldridge1988southeast].  The SEAMAP survey is a hydrographic trawl survey that has been conducted semi-annually in the northwestern Gulf  (-88 to -97.3 longitutde and 3-100 m depth) since 1987.  Bottom environmental conditions (e.g., temperatures, salinity, dissolved oxygen, depth) are measured at point locations chosen based on a stratified random sampling design using a conductivity, temperature, depth profiler (CTD).  Additionally, biological samples are collected using 40m trawl nets and captured biomass or samples of catch are measured weighed and identified to species for each station location.  Further details regarding the SEAMAP survey and sampling procedures can be found in Eldridge [@eldridge1988southeast] and the annual SEAMAP atlases [@rester2011seamap].  

Mapping and spatial statistics
A primary objective for this project is to examine the spatial and temporal variation of bycatch across the northwestern Gulf region. Previous studies focused on the Gulf shrimp fishery observer data set have evaluated the impacts on a given species [@XXXX] or most recently the species composition of bycatch over a number of years [@scott-dentonXXXX] however to our knowledge no through examination of the spatio-temporal dynamics of bycatch has been undertaken.  We plan to examine spatial and temporal heterogeneity in bycatch rate in a nested framework following the methods of XXXXX?  To evaluate questions of is the pattern of bycatch unifor across space we will conduct.... Additionally, given the spatial resolution of the Gulf shrimp fishery observer data we can utilize recent methods for the determination of hotspot locations for fishery bycatch. XXXX (date) used XX modeling to ....


Regression modeling

We propose using a generalized additive model (GAM) approach to investigate relationships between fishing effort and incidental capture rates withing the shrimp fishery using a spatial model formulation, or variable coefficient GAM approach [@hastie_varying-coefficient_1993;@wood_stable_2004;@wood_generalized_2006]. Variable coefficient models are a class of regression model that allow coefficients to vary smoothly as a function of another model variable [@hastie_varying-coefficient_1993].  Variable-coefficient models that map variation in the relationship between a response and predictor variable across space are often referred to as geospatial regression models [@wood_generalized_2006] and have recently be applied to a number of fishery related studies [@bacheler_spatial_2010;@bartolino_ontogenetic_2010;@ciannelli_phenological_2007;@ciannelli_non-additive_2012]. We have recently applied similar model to evaluating effect of seasonal hypoxia in the northwestern Gulf to fleet dynamics in the Gulf shrimp fishery (Fig ?).  

+Application
Identify papers showing issues with bycatch and how our results could fill gaps.

Improve assessment methods (ask Katie about a reference for the bycatch/seamap estimates)





## Detailed Budget Estimate (Do not list NMFS employee salaries):





## FUNDING REQUESTED (ONE YEAR):

**MARFIN Funding**:  
**Other Funding**:  
**Total Funding**:  


